# A simple Wizard to generate Rust Effects
import os

TEMPLATE = """
// ----------------------------------------------------
// EFFECT: {name}
// Description: {desc}
// Generated by Kanha Studio Wizard
// ----------------------------------------------------
#[pyfunction]
fn apply_{func_name}(data: Vec<u8>, width: usize, height: usize, intensity: f32) -> PyResult<Vec<u8>> {{
    let mut output = data.clone();
    
    // Process Pixels (RGBA)
    for chunk in output.chunks_exact_mut(4) {{
        let r = chunk[0] as f32;
        let g = chunk[1] as f32;
        let b = chunk[2] as f32;
        
        // --- YOUR CUSTOM MATH HERE ---
        // Current Logic: {math_desc}
        {math_logic}
        // -----------------------------
        
        chunk[0] = new_r as u8;
        chunk[1] = new_g as u8;
        chunk[2] = new_b as u8;
    }}
    
    Ok(output)
}}
"""

def main():
    print("Kanha Custom Effect Wizard 🧙‍♂️")
    name = input("Effect Name (e.g., Red Boost): ")
    func_name = name.lower().replace(" ", "_")
    
    print("\nChoose Logic Type:")
    print("1. Color Multiplier")
    print("2. Simple Invert")
    print("3. Brightness/Exposure")
    choice = input("Select [1-3]: ")
    
    math_logic = ""
    math_desc = ""
    
    if choice == '1':
        math_logic = "let new_r = r * intensity; let new_g = g; let new_b = b;"
        math_desc = "Multiplies Red channel by Intensity"
    elif choice == '2':
        math_logic = "let new_r = 255.0 - r; let new_g = 255.0 - g; let new_b = 255.0 - b;"
        math_desc = "Inverts Colors (Intensity ignored)"
    elif choice == '3':
        math_logic = "let new_r = (r * intensity).min(255.0); let new_g = (g * intensity).min(255.0); let new_b = (b * intensity).min(255.0);"
        math_desc = "Boosts brightness by Intensity factor"
        
    code = TEMPLATE.format(name=name, desc=math_desc, func_name=func_name, math_logic=math_logic, math_desc=math_desc)
    
    print("\n✅ GENERATED RUST CODE:\n")
    print(code)
    print("\n👉 COPY this into 'rust_engine/src/lib.rs'")
    print(f"👉 Don't forget to add: m.add_function(wrap_pyfunction!(apply_{func_name}, m)?)?;")

if __name__ == "__main__":
    main()